// <auto-generated />
using System;
using GanttChartAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GanttChartAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251216201645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GanttChartAPI.Models.AssignedTask", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("AssignedTasks");
                });

            modelBuilder.Entity("GanttChartAPI.Models.ClassInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMultiUse")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTeacherInvite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("GanttChartAPI.Models.ClassRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClassId")
                        .IsUnique();

                    b.ToTable("ClassRoles");

                    b.HasDiscriminator<string>("RoleType").HasValue("ClassRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GanttChartAPI.Models.ProjectSolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("ProjectSolutions");
                });

            modelBuilder.Entity("GanttChartAPI.Models.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("SolutionId");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("GanttChartAPI.Models.TaskDependency", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskId", "DependsOnTaskId");

                    b.HasIndex("DependsOnTaskId");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("GanttChartAPI.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GanttChartAPI.Models.TeamMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("GanttChartAPI.Models.TopicClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TopicClasses");
                });

            modelBuilder.Entity("GanttChartAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GanttChartAPI.Models.WorkProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TopicClassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TopicClassId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GanttChartAPI.Models.StudentRelation", b =>
                {
                    b.HasBaseType("GanttChartAPI.Models.ClassRole");

                    b.HasIndex("ClassId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("GanttChartAPI.Models.TeacherRelation", b =>
                {
                    b.HasBaseType("GanttChartAPI.Models.ClassRole");

                    b.HasIndex("ClassId");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("GanttChartAPI.Models.AssignedTask", b =>
                {
                    b.HasOne("GanttChartAPI.Models.ProjectTask", "ProjectTask")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GanttChartAPI.Models.User", "User")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GanttChartAPI.Models.ClassInvite", b =>
                {
                    b.HasOne("GanttChartAPI.Models.TopicClass", "Class")
                        .WithMany("Invites")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("GanttChartAPI.Models.ProjectSolution", b =>
                {
                    b.HasOne("GanttChartAPI.Models.WorkProject", "Project")
                        .WithMany("Solutions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GanttChartAPI.Models.Team", "Team")
                        .WithOne("Solution")
                        .HasForeignKey("GanttChartAPI.Models.ProjectSolution", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GanttChartAPI.Models.ProjectTask", b =>
                {
                    b.HasOne("GanttChartAPI.Models.ProjectTask", "ParentTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GanttChartAPI.Models.ProjectSolution", "Solution")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTask");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("GanttChartAPI.Models.TaskDependency", b =>
                {
                    b.HasOne("GanttChartAPI.Models.ProjectTask", "DependsOnTask")
                        .WithMany()
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GanttChartAPI.Models.ProjectTask", "Task")
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnTask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("GanttChartAPI.Models.Team", b =>
                {
                    b.HasOne("GanttChartAPI.Models.WorkProject", "Project")
                        .WithMany("Teams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GanttChartAPI.Models.TeamMember", b =>
                {
                    b.HasOne("GanttChartAPI.Models.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GanttChartAPI.Models.User", "User")
                        .WithMany("Teams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GanttChartAPI.Models.WorkProject", b =>
                {
                    b.HasOne("GanttChartAPI.Models.TopicClass", "TopicClass")
                        .WithMany("Projects")
                        .HasForeignKey("TopicClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicClass");
                });

            modelBuilder.Entity("GanttChartAPI.Models.StudentRelation", b =>
                {
                    b.HasOne("GanttChartAPI.Models.TopicClass", "TopicClass")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GanttChartAPI.Models.User", "User")
                        .WithMany("StudentClasses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicClass");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GanttChartAPI.Models.TeacherRelation", b =>
                {
                    b.HasOne("GanttChartAPI.Models.TopicClass", "TopicClass")
                        .WithMany("Teachers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GanttChartAPI.Models.User", "User")
                        .WithMany("TeacherClasses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicClass");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GanttChartAPI.Models.ProjectSolution", b =>
                {
                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("GanttChartAPI.Models.ProjectTask", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("Dependencies");

                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("GanttChartAPI.Models.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Solution")
                        .IsRequired();
                });

            modelBuilder.Entity("GanttChartAPI.Models.TopicClass", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Projects");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("GanttChartAPI.Models.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("StudentClasses");

                    b.Navigation("TeacherClasses");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("GanttChartAPI.Models.WorkProject", b =>
                {
                    b.Navigation("Solutions");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
